import Vue from 'vue';

import {
  CardPlugin,
  TablePlugin,
  InputGroupPlugin,
  LayoutPlugin,
  NavPlugin,
  PaginationPlugin,
  NavbarPlugin,
  ImagePlugin,
  IconsPlugin,
  SpinnerPlugin,
  JumbotronPlugin,
  FormInputPlugin,
  FormSelectPlugin,
  FormGroupPlugin,
  FormPlugin,
  FormCheckboxPlugin,
  FormRadioPlugin,
  ToastPlugin,
  TabsPlugin,
  ModalPlugin,
  MediaPlugin,
  ButtonGroupPlugin,
  ButtonPlugin,
  ButtonToolbarPlugin,
  AlertPlugin,
  BadgePlugin,
  CarouselPlugin,
  CollapsePlugin,
  DropdownPlugin,
  ListGroupPlugin,
  PopoverPlugin,
  BVToastPlugin,
  VBPopoverPlugin,
  VBTooltipPlugin,
  VBScrollspyPlugin
} from 'bootstrap-vue';

Vue.use(CardPlugin);
Vue.use(TablePlugin);
Vue.use(InputGroupPlugin);
Vue.use(LayoutPlugin);
Vue.use(NavPlugin);
Vue.use(PaginationPlugin);
Vue.use(NavbarPlugin);
Vue.use(ImagePlugin);
Vue.use(IconsPlugin);
Vue.use(SpinnerPlugin);
Vue.use(JumbotronPlugin);
Vue.use(FormInputPlugin);
Vue.use(FormSelectPlugin);
Vue.use(FormGroupPlugin);
Vue.use(FormPlugin);
Vue.use(FormCheckboxPlugin);
Vue.use(FormRadioPlugin);
Vue.use(ToastPlugin);
Vue.use(TabsPlugin);
Vue.use(ModalPlugin);
Vue.use(MediaPlugin);
Vue.use(ButtonGroupPlugin);
Vue.use(ButtonPlugin);
Vue.use(ButtonToolbarPlugin);
Vue.use(AlertPlugin);
Vue.use(BadgePlugin);
Vue.use(CarouselPlugin);
Vue.use(CollapsePlugin);
Vue.use(DropdownPlugin);
Vue.use(ListGroupPlugin);
Vue.use(PopoverPlugin);
Vue.use(BVToastPlugin);

Vue.use(VBPopoverPlugin);
Vue.use(VBTooltipPlugin);
Vue.use(VBScrollspyPlugin);
